server:
 port: 9191
 
spring:
 application:
   name: API-GATEWAY

 cloud:
   gateway:
     routes:
     - id: COLLEGE-SERVICE
       uri: lb://COLLEGE-SERVICE
       predicates:
       - Path=/college/**
     - id: STUDENT-SERVICE
       uri: lb://STUDENT-SERVICE
       predicates:
       - Path=/student/**
     

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8671/eureka/
 instance:
   hostname: localhost  